### ISSUE TITLE
add codesandbox environment

### ISSUE THREAD

**Issue by michaelneale** [TBD54566975/tbdex-pfi-exemplar#12]
It would be nice to be able to launch this example in a codesandbox instance (with postgres etc). 

cc @blackgirlbytes @acekyd

**Comment by acekyd** [comment]
Got feedback from the CSB team that this is possible. Will give it a go next week. @michaelneale

**Comment by michaelneale** [comment]
@acekyd no worries - would help for any contributors/hacktoberfest like thingies (not sure if any are imminent @angiejones) was main driver. Let me know how you go - if falls off your plate tag me as I am trying to update an example sometime so may get to it.

**Comment by acekyd** [comment]
Hi @michaelneale, gave this a shot with the config needed to have this running on CSB but I'm stuck and unable to run the postgres commands. 

You can take a look (and fork) this [project](https://codesandbox.io/p/devbox/old-bush-nl6yxy) in case I'm missing something. Thanks

**Comment by michaelneale** [comment]
@acekyd can you give this a try: https://github.com/TBD54566975/tbdex-pfi-exemplar?tab=readme-ov-file#running-in-codesandbox using a devbox - see if you wait for a hit and can follow the steps to run the pFI?

**Comment by acekyd** [comment]
Awesome!! I was able to fork that devbox and got it running [here](https://codesandbox.io/p/devbox/elegant-lewin-jcmfd7) @michaelneale.

Heads up, CodeSandbox won't show the .env file in the explorer so it has to be set after running the command in `logo dropdown > Settings > Environment variables > Plain text`. 
![Screenshot 2024-01-19 at 15 58 02](https://github.com/TBD54566975/tbdex-pfi-exemplar/assets/4003538/520c0436-f267-493e-a253-51a79b45dc04)

**Comment by michaelneale** [comment]
I guess should as @angiejones if this approach is scalable for people trying it out en-mass?

**Comment by acekyd** [comment]
I'll automate the server steps a bit - with CSB tasks. And should be good to go.

**Comment by acekyd** [comment]
Good enough to close the issue! @michaelneale. Tried to automate the db commands but CSB runs them synchronously instead. So I think this current setup works.
